# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  
  pull_request:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create new branch
        run: git checkout -b feature-branch

      - name: Create file and add content
        run: echo "hai this is the current branch:${{ github.event.pull_request.head.ref }}" > new_file.txt

      - name: Commit and push
        run: |
          git add new_file.txt
          git commit -m "Added new file with branch information"
          git push origin feature-branch

      - name: Create pull request
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');
            const github = require('@actions/github');

            async function run() {
              try {
                const token = core.getInput('GITGUBSECRET');
                const   
                  octokit = new github.Octokit({ auth: token });

                const { data: pull_request } = await octokit.pulls.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  head: 'feature-branch',
                  base: context.payload.pull_request.base.ref,
                  title: 'New feature from action',
                  body: 'This pull request was created by a GitHub Action'
                });

                core.setOutput('pull_request_number', pull_request.number);
              } catch (error) {
                core.setFailed(error.message);
              }
            }

            run();
          GITHUB_TOKEN: ${{ secrets.GITGUBSECRET }}
